server.port=8082
spring.application.name=transfer-orchestrator

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=2000

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Downstream Service URLs
services.risk.url=${RISK_SERVICE_URL:http://localhost:8084}
services.account.url=${ACCOUNT_SERVICE_URL:http://localhost:8081}
services.cbs.url=${CBS_SERVICE_URL:http://localhost:8085}

# Resilience4j Circuit Breaker
resilience4j.circuitbreaker.instances.cbsService.sliding-window-size=10
resilience4j.circuitbreaker.instances.cbsService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.cbsService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.cbsService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.cbsService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.cbsService.ignore-exceptions=\
    org.springframework.web.server.ResponseStatusException,\
    org.springframework.web.reactive.function.client.WebClientResponseException,\
    org.springframework.web.reactive.function.client.WebClientResponseException$BadRequest,\
    org.springframework.web.reactive.function.client.WebClientResponseException$NotFound,\
    org.springframework.web.reactive.function.client.WebClientResponseException$Forbidden,\
    org.springframework.web.reactive.function.client.WebClientResponseException$UnprocessableEntity

# Resilience4j Retry
resilience4j.retry.instances.cbsService.max-attempts=3
resilience4j.retry.instances.cbsService.wait-duration=300ms
resilience4j.retry.instances.cbsService.enable-exponential-backoff=true
resilience4j.retry.instances.cbsService.exponential-backoff-multiplier=2
resilience4j.retry.instances.cbsService.ignore-exceptions=\
    org.springframework.web.server.ResponseStatusException,\
    org.springframework.web.reactive.function.client.WebClientResponseException,\
    org.springframework.web.reactive.function.client.WebClientResponseException$BadRequest,\
    org.springframework.web.reactive.function.client.WebClientResponseException$NotFound,\
    org.springframework.web.reactive.function.client.WebClientResponseException$Forbidden,\
    org.springframework.web.reactive.function.client.WebClientResponseException$UnprocessableEntity

# Management Endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always
