# =========================================================================
# CAPSTONE FSE: Account & Identity Service
# Cloud Native Production Profile: Microsoft Azure (Azure SQL + Azure Redis)
# =========================================================================

spring.application.name=account-service
server.port=8081

# =========================================================================
# AZURE SQL DATABASE (Master Relational State)
# =========================================================================
spring.datasource.url=${AZURE_SQL_URL:jdbc:sqlserver://sql-banking-master.database.windows.net:1433;databaseName=sqldb-master;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;}
spring.datasource.username=${AZURE_SQL_USERNAME:fse_admin}
spring.datasource.password=${AZURE_SQL_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.datasource.hikari.pool-name=HikariPool-AccountService
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000

spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# =========================================================================
# AZURE CACHE FOR REDIS (RTR, Token Blacklist & Active Sessions)
# =========================================================================
spring.data.redis.host=${AZURE_REDIS_HOST:redis.banking.svc.cluster.local}
spring.data.redis.port=${AZURE_REDIS_PORT:6379}
spring.data.redis.ssl.enabled=${AZURE_REDIS_SSL:false}
spring.data.redis.password=${AZURE_REDIS_KEY:}
spring.data.redis.timeout=3000

# Actuator & Observability
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}

# OpenTelemetry Distributed Tracing
management.tracing.sampling.probability=${OTEL_SAMPLING_PROBABILITY:1.0}
management.tracing.propagation.type=W3C
management.tracing.baggage.correlation.enabled=true
management.otlp.tracing.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}
management.otlp.tracing.transport=http

jwt.secret=${JWT_SECRET:c3VwZXItc2VjcmV0LWtleS1mb3ItZnNlLWNhcHN0b25lLWJhbmtpbmctcGxhdGZvcm0tMjAyNi0xMjM0NTY3ODkwMTI=}
jwt.expiration-ms=900000
jwt.refresh-expiration-ms=604800000
